set /P VERSION=<VERSION
echo "version = %VERSION%"
set PACKAGE=AnumbyMasterMind
set PASS=pypi-AgEIcHlwaS5vcmcCJDE3ZWY3MWI1LWVjNjYtNGQwMi1iYmRkLWI0ZGM3M2UwMDNjNAACGFsxLFsiYW51bWJ5bWFzdGVybWluZCJdXQACLFsyLFsiMWMyOTc5MjItMGUyZS00ZTNjLTlkZGYtMzI4MGFkMDEyZjRmIl1dAAAGILzRXEC3qMSKKOkLUwUMV6agdxyBj8tiqNunFBSICavZ
twine upload --verbose -u __token__ -p "%PASS%" dist\%PACKAGE%-%VERSION%*.*
